### ISSUE TITLE
Handle leak on Android

### ISSUE THREAD

**Issue by vjjjv** [graeme-hill/crossguid#10]
I believe this should be added to Android code in the end of function GuidGenerator::newGuid()

`
_env->DeleteLocalRef(javaUuid);
`

.. otherwise it will overload the handle count on heavy use.

**Comment by graeme-hill** [comment]
Oh that sounds bad. I will look into this when I get a sec. And yes I know that doesn't sound promising given that it took me over a year to respond :)
