### ISSUE TITLE
How set up preprocessor definitions.

### ISSUE THREAD

**Issue by darkwind666** [graeme-hill/crossguid#2]
Hello mr Graeme Hill. Thank you for good library. It will be good to point in readme how set preprocessors flags in some ide like visual studio 2012 -> project properties->Configuration properties-> C/C++ -> Preprocessor -> Preprocessor Definitions (type you platform defenition(GUID_LIBUUID, GUID_CFUUID, GUID_WINDOWS, GUID_ANDROID )  ). Best regards.

**Comment by graeme-hill** [comment]
You don't need to do it manually anymore because the project uses cmake. Regarding information on how to setup preprocessor flags in general, I think google and SO are going to be better at answering that anyways because it is not specific to this project.
