### ISSUE TITLE
Makefile does not match source

### ISSUE THREAD

**Issue by therealbstern** [graeme-hill/crossguid#21]
The source package for v0.2.1 contains `Guid.cpp` and `Guid.hpp`.
- The Makefile expects `guid.cpp` and `guid.h`.
- Internally, `Guid.cpp` expects `Guid.hpp`.

This breaks the build (doubly so on case-sensitive filesystems).

**Comment by graeme-hill** [comment]
You mean the Makefile generated by cmake? I just downloaded crossguid-0.2.1.tar.gz on linux (case sensitive filesystem) and it builds just fine with the following commands:

```bash
mkdir build
cd build
cmake ..
make
``` 

I also checked the Makefile that was generated and it has the file names properly capitalized.

**Comment by therealbstern** [comment]
This is my fault, it's a problem with the build script I was using.  I apologize.

**Comment by graeme-hill** [comment]
Don't worry about it :)
