### ISSUE TITLE
[Android] Continuous usage causes local references leak and app crash

### ISSUE THREAD

**Issue by thedilletante** [graeme-hill/crossguid#22]
Hi! Thanks for the great library.
We use your library in our project and faced with an issue. We start new thread in native code and perform operations including generating of multiple `uuid`s. After some time the application crashes with native stacktrace like following:
```
art/runtime/indirect_reference_table.cc:115] JNI ERROR (app bug): local reference table overflow (max=512)
art/runtime/indirect_reference_table.cc:115] local reference table dump:
art/runtime/indirect_reference_table.cc:115]   Last 10 entries (of 512):
...
art/runtime/indirect_reference_table.cc:115]       508: 0x12d94490 java.util.UUID
...
art/runtime/indirect_reference_table.cc:115]       505: 0x12c05f30 java.util.UUID
...
art/runtime/indirect_reference_table.cc:115]       502: 0x12c05ec8 java.util.UUID
art/runtime/indirect_reference_table.cc:115]   Summary:
...
art/runtime/indirect_reference_table.cc:115]       181 of java.util.UUID (181 unique instances)
```
It seems that `jobject javaUuid` local reference in `Guid newGuid()`, returned from `randomUUID()` java method should be deleted after bits evaluation. 

Also, as far as `newGuid()` is callable from different threads after `initJni()` `AndroidGuidInfo.uuidClass` must be a global reference to prevent illegal usage and crash.

Is it suitable to open PR with implementation of this behaviour?

**Comment by thedilletante** [comment]
Sorry, the issue is intended for previous version of code. I reviewed the new version of code and found that `javaUuid` is deleted now.
However, `AndroidGuidInfo.uuidClass` is local reference yet.

**Comment by graeme-hill** [comment]
thanks
