### ISSUE TITLE
Fix constructor std::array error on CLang 9.0.0

### ISSUE THREAD

**Issue by strongmindsmhs** [graeme-hill/crossguid#27]
On Clang (9.0.0) the following error is reported:
error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
Guid::Guid() : _bytes{ 0 }
                       ^
                       {}
/Users/dk8mohos/Projects/LPFPlatform/3rdParty/crossguid/Guid.cpp:290:3: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
                bytes.byte0,
                ^~~~~~~~~~~~
2 errors generated.

A quick fix would be adding "-Wno-missing-braces" to the compiler flags (APPLE).

**Comment by gabyx** [comment]
Fixed in PR  #28
