### ISSUE TITLE
Help documentation problem on the cmake command

### ISSUE THREAD

**Issue by jplflyer** [graeme-hill/crossguid#32]
README.me says to invoke cmake like this:

cmake .. -DCMAKE_INSTALL_PREFIX="/usr/local/include"

Doing so results in an installation underneath this directory. That is, these directories are created:

/usr/local/include/lib
/usr/local/include/include
/usr/local/include/include/crossguid

That cmake command should probably exclude the /include part at the end. This was on a Mac. I presume it's a similar issue on other platforms.

**Comment by graeme-hill** [comment]
thanks will change readme
