### ISSUE TITLE
std::hash<Guid> implementation for use with std containers

### ISSUE THREAD

**Issue by antiprosynthesis** [graeme-hill/crossguid#4]
Here's a little piece of code that can be added to be able to use Guid as key for containers like std::unordered_map:

``` c++
namespace std
{
template<>
struct hash<Guid>
{
    size_t operator()(const Guid &guid) const
    {
        stringstream ss;
        ss << guid;
        return hash<string>()(ss.str());
    }
};
}
```

**Comment by fish2000** [comment]
Oh wow I just submitted PR #6, with similar implementation (I also expanded stringification, to sidestep the need for the relatively heavyweight `std::stringstream` invocation). Great minds, yes!

**Comment by Justinzobel** [comment]
@fish2000 @antiprosynthesis I'd suggest getting together and forking this as it seems abandoned. If you do please tag me here :)

**Comment by eliaskosunen** [comment]
@Justinzobel I maintain a fork of this repo that implements this and many other™ features: https://github.com/eliaskosunen/crossguid

**Comment by graeme-hill** [comment]
I just merged it and made a few tweaks to make it compile in android.
