### ISSUE TITLE
Now require C++17?

### ISSUE THREAD

**Issue by asmaloney** [graeme-hill/crossguid#47]
Commit d9e6cd1d489062772f72b829e12cb354d804cffe added `std::string_view` which was introduced in C++17.

Did you intend to require C++17 from now on? (FWIW I am using crossguid with C++11.)

Thanks!

**Comment by jplflyer** [comment]
This is insanely annoying.

**Comment by asmaloney** [comment]
I'm sure it's just an oversight. You can just pin your repo to b151b7d1aeb68c4b9e98a8a2e0a547885aa0b60c until it's sorted out.

**Comment by zhuqiang00099** [comment]
because std::string_view  ,it must use vs2017 on windows , one way to slove it , just use const std::string to replace std::string_view, but may be  lower performance ?

**Comment by lp35** [comment]
I don't agree with this bump for C++17. We painfully switched to C++11 last year, and we need to support Centos 7 with GCC4. You should keep your library C++11 compatible!

**Comment by MilhouseVH** [comment]
This change prevents LibreELEC (and in general, Kodi on Linux) from using the latest version of this library - we'll probably have to stay on https://github.com/graeme-hill/crossguid/commit/b151b7d1aeb68c4b9e98a8a2e0a547885aa0b60c forever or find an alternative repo if this isn't reverted.

**Comment by asmaloney** [comment]
Just a minor point - #50 doesn't really "fix" this particular issue because I'm asking about intent.

We need to hear from @graeme-hill to see if he intends to require C++17 from now on.

If so, then that PR is useful.

**Comment by asmaloney** [comment]
After [setting up a fork to only require C++11](https://github.com/asmaloney/crossguid) and then coming here to let people know, I ran across [Elias's fork](https://github.com/eliaskosunen/crossguid)!

Mine is a basic fork with the C++17 stuff not included and a better Travis setup. Elias changed a lot more. In his words:

> Its interface is not backwards-compatible (see README for changes and usage), and it lacks Android support, but it has the added advantage of, among other things, supporting C++11, and being alive with an active maintainer (me!).

Have fun!
