### ISSUE TITLE
Fork of crossguid

### ISSUE THREAD

**Issue by eliaskosunen** [graeme-hill/crossguid#52]
With many of the issues here being unaddressed, and @graeme-hill being rather unresponsive, I though I'd release my previously private fork to the public to use. You can find it here: https://github.com/eliaskosunen/crossguid.

Its interface is not backwards-compatible (see README for changes and usage), and it lacks Android support, but it has the added advantage of, among other things, supporting C++11, and being alive with an active maintainer (me!).

Go take a look and give it a try, if you want to.

**Comment by graeme-hill** [comment]
I fully support this :+1: I still maintain this but not closely.
