### ISSUE TITLE
that is not cross platform at all

### ISSUE THREAD

**Issue by songtzu** [graeme-hill/crossguid#7]
you just warper some lib in a class.
THAT IS NOT CROSS PLATFORM

**Comment by vapier** [comment]
this bug report is useless.  please don't post crap.

**Comment by songtzu** [comment]
@vapier 
am I wrong? I just tell the fact. This lib just wraper a third part (luuid) lib under linux together with GUID which under windows. I don't think this is the so called cross platform. since a uuid/guid lib is rather small. it should not depend on other lib.
show me your useful report.

**Comment by vapier** [comment]
nothing you've written is news.  read the README.

**Comment by graeme-hill** [comment]
> you just warper some lib in a class

ya that's exactly the point
