### ISSUE TITLE
Symbols are not exported when built with LTO

### ISSUE THREAD

**Issue by candrews** [graeme-hill/crossguid#8]
When built using LTO:
CFLAGS="${CFLAGS} -flto"
CXXFLAGS="${CXXFLAGS} -flto"
LDFLAGS="${LDFLAGS} -flto"

no symbols are exported:
$ readelf -sW /usr/lib64/libcrossguid.a | c++filt | grep Guid::Guid
returns nothing.

**Comment by graeme-hill** [comment]
Sounds like perfect optimization. Seriously though I have not idea how that works but will look into it if I get a sec. For now just gonna leave this open.

**Comment by graeme-hill** [comment]
From what I'm reading it looks like this is a common issue with using LTO and static libraries. I think this has to do with the tools/commands being used and is not actually a bug in the program itself.
